{
 "title": "Promfetcher",
 "tags": [
  "tools",
  "prometheus",
  "promfetcher"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Gorouter errors",
   "type": "stat",
   "description": "Promfetcher cannot retrieve gorouter route table (maximum occurrences during the selected period).",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } }
  },
  {
   "title": "Failure percentage",
   "type": "timeseries",
   "description": "Promfetcher percentage of failures to fetch Apps metrics endpoints",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(promfetch_metric_fetch_failed_by_app > 0) / count(promfetch_metric_fetch_failed_by_app)"
    }
   ]
  },
  {
   "title": "Successful fetch per Apps",
   "type": "timeseries",
   "description": "Number of successful fetch to Apps metrics endpoints by applications (top 7).",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/mn" } },
   "targets": [
    {
     "expr": "topk(7, sum by(organization_name, space_name, app_name) (rate(promfetch_metric_fetch_success_total[15m]) > 0))*60",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }}"
    },
    {
     "expr": "sum(rate(promfetch_metric_fetch_success_total[15m]) > 0)*60",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Failures per Apps",
   "type": "timeseries",
   "description": "Number of unsuccessful fetch Apps metrics endpoints by applications (top 7).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/mn" } },
   "targets": [
    {
     "expr": "topk(7, sum by(organization_name, space_name, app_name) (rate(promfetch_metric_fetch_failed_total[15m]) > 0))*60",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }}"
    },
    {
     "expr": "sum(rate(promfetch_metric_fetch_failed_total[15m]) > 0)*60",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Successful fetch per Apps",
   "type": "timeseries",
   "description": "Number of successful fetch to Apps metrics endpoints by applications (top 7).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/mn" } },
   "targets": [
    {
     "expr": "topk(7, sum by(organization_name, space_name, app_name) (rate(promfetch_metric_fetch_success_total[15m]) > 0))*60",
     "legendFormat": "{{ organization_name }} / {{ space_name }} / {{ app_name }}"
    },
    {
     "expr": "sum(rate(promfetch_metric_fetch_success_total[15m]) > 0)*60",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Explore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric fetch per minute",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "label_join(\n sum by(organization_name, space_name, app_name) (rate(promfetch_metric_fetch_success_total[5m]))>0,\n\"join\", \":\", \"organization_name\", \"space_name\", \"app_name\")*60",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\n sum by(organization_name, space_name, app_name) (rate(promfetch_metric_fetch_failed_total[5m]))>0,\n\"join\", \":\", \"organization_name\", \"space_name\", \"app_name\")*60",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}